### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by kequach** [cjvanlissa/storm_meta_father_mother#5]
I saw that a license file should be included according to the README but it is missing.

**Comment by cjvanlissa** [comment]
Dear Keven,
I appreciate your involvement, but please consider whether the issues you open on many repositories that you are not a contributor to could be interpreted as "toxic behavior". For a recent study on toxic behavior in open source communities that illustrates the kind of behavior this refers to, see: https://www.cs.cmu.edu/afs/cs.cmu.edu/Web/People/ckaestne/pdf/icse22_toxicity.pdf

Take care,
Caspar
